# Generated by Django 3.2.9 on 2021-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AClass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=300)),
                ('prof_name', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=300)),
            ],
        ),
    ]
